/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleSearchStarterIndexRouteImport } from './routes/people-search/starter/index'
import { Route as PeopleSearchSubmissions01IndexRouteImport } from './routes/people-search/submissions/01/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSearchStarterIndexRoute =
  PeopleSearchStarterIndexRouteImport.update({
    id: '/people-search/starter/',
    path: '/people-search/starter/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PeopleSearchSubmissions01IndexRoute =
  PeopleSearchSubmissions01IndexRouteImport.update({
    id: '/people-search/submissions/01/',
    path: '/people-search/submissions/01/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/people-search/starter/': typeof PeopleSearchStarterIndexRoute
  '/people-search/submissions/01/': typeof PeopleSearchSubmissions01IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/people-search/starter': typeof PeopleSearchStarterIndexRoute
  '/people-search/submissions/01': typeof PeopleSearchSubmissions01IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/people-search/starter/': typeof PeopleSearchStarterIndexRoute
  '/people-search/submissions/01/': typeof PeopleSearchSubmissions01IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/people-search/starter/' | '/people-search/submissions/01/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/people-search/starter' | '/people-search/submissions/01'
  id:
    | '__root__'
    | '/'
    | '/people-search/starter/'
    | '/people-search/submissions/01/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PeopleSearchStarterIndexRoute: typeof PeopleSearchStarterIndexRoute
  PeopleSearchSubmissions01IndexRoute: typeof PeopleSearchSubmissions01IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people-search/starter/': {
      id: '/people-search/starter/'
      path: '/people-search/starter'
      fullPath: '/people-search/starter/'
      preLoaderRoute: typeof PeopleSearchStarterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people-search/submissions/01/': {
      id: '/people-search/submissions/01/'
      path: '/people-search/submissions/01'
      fullPath: '/people-search/submissions/01/'
      preLoaderRoute: typeof PeopleSearchSubmissions01IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PeopleSearchStarterIndexRoute: PeopleSearchStarterIndexRoute,
  PeopleSearchSubmissions01IndexRoute: PeopleSearchSubmissions01IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
